#+TITLE: Frederick


Attraction effect is represented in which product dimension is represented by a number
- Durability rating: 7.2

Non-numerical examples failed to show the attraction effect
- believed to be due to range effects / "trade-off contrast"
  + parducci 1974 for more detail
  + in comparing:
    A = (25 MPG; $25,000)
    B = (35 MPG; $35,000)
    C = (36 MPG; $42,000)

    consider that numerical gives us a valued tradeoff between A and B.  35 - 25 & 25k, 35k, -> 1 MPG = $1k.  However, if we consider B to C, then 1 MPG = $7k.

Why is it in table 3 that numeric vs visual just overwhelmingly has lower choices systemically for the target, in the 2-choice lineup?

not entirely understanding that "shrinking" stuff

In summary: the attraction effect does not occur in cases where numeric representation is not present along one of the dimensions.

What about in a 1 vs 2 choice lineup?
- Seth told me about a breadmaker being presented, where people were not buying it at all.  Then, a new product was presented, that was "over-engineered" and sales of the original increased after that point.
