#+TITLE: Trueblood

Context effects are fundamental to decision making -> context effects are shown at a deeper perceptual level than higher numbers.
- This seems to be in contrast with the previous paper, however, the studies show stimuli that are quantifiably larger/smaller.

* The attraction effect
* Similarity Effect
Where two similar choices that are equally competitive with a dissimilar third choice, P(third choice) increases
* Compromise Effect
When a "middle-ground" choice is presented, it is selected the most often:
- For MPG & Price standpoint, imagine a C: 30 MPG, $30k.  Middle of A & B, would be chosen theoretically the most.

Apparently, attraction & compromise effects increase with deliberation time.

Multialternative-decision-field theory (MDFT; Roe et al.)
Leaky-competing-accumulators (LCA) model (Usher & McClelland)


* Random thought
So in the context of consumer choice, and imagining the "applied scenario," what about the option to not purchase anything, and carry over that balance to other future choices?  Would we see consistent context effects in this scenario?
